SERVER_IP = '127.0.0.1'
SERVER_PORT = 9099 

MSG_NONE                = 0 
CL_MSG_AUTH             = 1 
SV_MSG_AUTH_RESPONSE    = 2 
CL_MSG_CHAT             = 3 
SV_MSG_CHAT             = 4 
CL_MSG_DISCONNECT_REQ   = 5 
SV_MSG_DISCONNECT_ACK   = 6

SV_MSG_START_GAME       = 10
SV_MSG_UPDATE_POSITIONS = 11
SV_MSG_UPDATE_STATES    = 12

CL_MSG_COMPLETE_SETUP   = 20

CL_MSG_PERFORM_WALK     = 50
CL_MSG_PERFORM_CLOUT    = 51
CL_MSG_PERFORM_JUMP     = 52
CL_MSG_PERFORM_CHARGE   = 53

CL_MSG_COMPLETE_WALK    = 60
CL_MSG_COMPLETE_JUMP    = 62
CL_MSG_COMPLETE_CHARGE  = 64